# Generated by Django 4.2.6 on 2023-11-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_alter_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='ano_publicacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de Publicación'),
        ),
    ]
